# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0005_auto_20180131_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_name',
            field=models.CharField(max_length=50),
        ),
    ]
